title: "Jeyih Lin"
description: "A Plumer with Nothing to Lose"
theme: minima
url: "https://jeyihlin.github.io"

author:
  name: "Jeyih Lin"
  email: "jeyihlin@gmail.com"
  github: "jeyihlin"

# Navigation links (must match filenames)
header_pages:
  - index.md
  - about.md
  - projects.md
  - blog.md

minima:
  social_links:
    github: "jeyihlin"
